# Generated by Django 3.2.13 on 2022-12-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=150)),
                ('grad_year', models.IntegerField()),
                ('degree_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_role', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('start_date', models.SlugField(max_length=20)),
                ('end_date', models.SlugField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Extracurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_role', models.CharField(max_length=150)),
                ('org_name', models.CharField(max_length=150)),
                ('start_date', models.SlugField(max_length=20)),
                ('end_date', models.SlugField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('objective', models.TextField()),
                ('phone', models.SlugField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='OtherLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_link', models.URLField()),
                ('medium_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.SlugField()),
                ('skill_name', models.SlugField()),
            ],
        ),
    ]
