# Generated by Django 3.2.13 on 2022-12-31 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221231_0356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experience',
            new_name='ExperienceCard',
        ),
    ]
