# Generated by Django 3.2.13 on 2022-12-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221231_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sender_email', models.EmailField(max_length=254)),
                ('message_subject', models.CharField(max_length=100)),
                ('message_content', models.TextField()),
            ],
        ),
    ]
